### ISSUE TITLE
Support for Apple M1 chip

### ISSUE THREAD

**Issue by LaVielle** [Scandit/scandit-react-native-datacapture-core#11]
I noticed that scandit-react-native-datacapture-core 6.11.0 and scandit-react-native-datacapture-barcode 6.11.0 add the following flag to my XCode project:
```
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64
```
This prevents my app from building on an M1 chip without Rosetta workaround.

Any idea when you might add support for M1?

**Comment by calebmackdavenport** [comment]
I don't deny that this is an overstep that is should be resolved on scandit's end, but you might be able to resolve this via something like this inside your podfile, at the bottom of the `target 'app' do` block

```java
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ""
  end
end
```

**Comment by ScanditSupport** [comment]
Hi 
 
Please accept my apologies for the issues you are experiencing.
The reason for the issue is that we have not yet migrated the react native plugins to XCFrameworks yet while it was done already for native iOS.
We are working on the migration for our plugins in the next versions but I don't have a confirmation yet w.r.t. to the SDK version.

In case you want us to notify once the changes are released, please reach out to us directly:
https://support.scandit.com/hc/en-us/requests/new

Best regards
Scandit Support
